"""The Armory renderer: one SDK mod that carries several pipeline weapons and a spawn console.

Each weapon is rendered by :func:`bl2_partgen.templates.render_mod` in *component* mode
(the ordinary generated module minus its ``build_mod`` call) into ``weapons/<id>.py``; the
module rendered here imports them, wires every component's hooks into one ``build_mod``,
enables them (F8) and adds the spawn surface: a console command, a menu page and a keybind.

Like :mod:`.templates`, this is ``string.Template`` substitution and nothing cleverer, so
the templates must never contain a literal ``$``.
"""

from __future__ import annotations

from string import Template
from typing import Any

from .resolve import ResolvedSpec
from .spec import ArmorySpec, ArmoryWeapon

__all__ = ["render_armory", "render_armory_pyproject", "render_armory_readme"]


_ARMORY = Template('''"""$mod_name -- the Armory: $count pipeline weapon(s) in one SDK mod, with a spawn console.

Generated by bl2_partgen from $spec_name. Do not edit by hand: change the armory spec (or a
weapon's own spec) and re-emit.

Each weapon is a component module under weapons/ -- the ordinary bl2_partgen render of its
own spec, minus build_mod. A component registers its package, fragments, parts, balance,
title and material at the main menu through its own menu_tick hook and keeps its own save
round-trip (F18) and prefix hooks. This module wires every component's hooks into ONE mod,
enables them (F8), and adds the spawn surface:

  console   armory list
            armory spawn <id> [--level N] [--no-equip]
            armory census
  menu      Armory > Weapon (dropdown) + Spawn selected (button)
  keybind   $key: spawn the selected weapon

Spawning borrows one mission's reward table ($mission), grants, and puts the table back
RESTORE_TICKS later through the registry every pipeline mod shares (F26), so any number of
pipeline mods may spawn through the same mission without corrupting it.

Unattended evidence (src/bl2_verify/armory_check.py): control.json {"auto_spawn": [ids]}
makes every gameplay map load write a census_on_load record, spawn each id in turn on the
wall clock, and end with a census + {"done": true}. Without that key nothing runs on its own.

Weapons:
$weapon_summary
"""

from __future__ import annotations

import json
import os
import sys
import time
import types
from typing import Any

import unrealsdk
from mods_base import (
    ButtonOption,
    DropdownOption,
    NestedOption,
    build_mod,
    command,
    get_pc,
    hook,
    keybind,
)
from unrealsdk.hooks import Type
from unrealsdk.unreal import BoundFunction, UObject, WrappedStruct

from .weapons import $imports

try:  # optional: a HUD toast when a weapon is spawned (ui_utils.sdkmod)
    from ui_utils import show_hud_message
except Exception:  # noqa: BLE001
    show_hud_message = None

__version__ = "$version"
__author__ = "$author"

# --------------------------------------------------------------------- what we carry
MOD_NAME = "$mod_name"
MOD_DIR = os.path.dirname(os.path.abspath(__file__))
#: optional; {"status_path": "..."} redirects the status JSON for the verify loop
CONTROL_FILE = os.path.join(MOD_DIR, "control.json")
DEFAULT_STATUS_FILE = os.path.join(MOD_DIR, "status.json")
#: the mission whose reward table spawn() borrows
SPAWN_MISSION = "$mission"
SPAWN_KEY = "$key"
#: viewport ticks the reward table stays hijacked before it is put back (F26)
RESTORE_TICKS = 300
#: seconds after a grant before the new weapon is equipped: the grant lands a few ticks
#: after ServerGrantMissionRewards returns, and tick counts scale with the frame rate (F25)
EQUIP_DELAY = 0.75

WEAPONS: tuple[dict[str, Any], ...] = (
$weapons
)
BY_ID = {w["id"]: w for w in WEAPONS}
BY_LABEL = {w["label"]: w for w in WEAPONS}
OUR_BALANCES = frozenset(w["balance"] for w in WEAPONS)
COMPONENTS = tuple(w["module"].COMPONENT for w in WEAPONS)
SLOT_FIELDS = COMPONENTS[0]["slot_fields"]


# --------------------------------------------------------------------- plumbing
def _log(message: str) -> None:
    unrealsdk.logging.info(f"[{MOD_NAME}] {message}")


def _control() -> dict[str, Any]:
    try:
        with open(CONTROL_FILE, encoding="utf-8") as handle:
            return json.load(handle)
    except Exception:  # noqa: BLE001 - a missing/broken control file must never break the mod
        return {}


_status: list[dict[str, Any]] = []


def _write(record: dict[str, Any]) -> dict[str, Any]:
    """Append a record to the status JSON (spawns, censuses; the components keep their own)."""
    record["t"] = time.time()
    _status.append(record)
    try:
        path = str(_control().get("status_path") or DEFAULT_STATUS_FILE)
        os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
        with open(path, "w", encoding="utf-8") as handle:
            json.dump(_status, handle, indent=1, default=str)
    except Exception as ex:  # noqa: BLE001
        _log(f"status write failed: {ex!r}")
    return record


def _hud(text: str) -> None:
    _log(text)
    if show_hud_message is not None:
        try:
            show_hud_message(MOD_NAME, text)
        except Exception:  # noqa: BLE001 - the HUD helper may fail silently by design
            pass


def registration() -> dict[str, Any]:
    """Each component's last menu_setup record (None until the main menu has registered it)."""
    out: dict[str, Any] = {}
    for weapon in WEAPONS:
        records = [r for r in weapon["module"]._status if r.get("phase") == "menu_setup"]
        out[weapon["id"]] = records[-1] if records else None
    return out


# --------------------------------------------------------------------- census
def _weapon_id(balance_path: str) -> str | None:
    return next((w["id"] for w in WEAPONS if w["balance"] == balance_path), None)


def _describe(weapon: UObject) -> dict[str, Any]:
    definition = weapon.DefinitionData
    balance = definition.BalanceDefinition
    balance_path = balance._path_name() if balance is not None else None
    entry: dict[str, Any] = {
        "weapon": weapon._path_name(),
        "id": _weapon_id(balance_path) if balance_path else None,
        "balance": balance_path,
        "slot": int(weapon.QuickSelectSlot),
        "unique_id": int(definition.UniqueId),
    }
    for field in SLOT_FIELDS:
        part = getattr(definition, field, None)
        if part is not None:
            entry[field] = part._path_name()
    for attr in ("FirstPersonMesh", "ThirdPersonMesh"):
        component = getattr(weapon, attr, None)
        mesh = getattr(component, "SkeletalMesh", None) if component is not None else None
        entry[attr] = mesh._path_name() if mesh else None
    return entry


def _our_weapons() -> list[tuple[int, UObject]]:
    """Every weapon of one of our balances the pawn owns, oldest first."""
    controller = get_pc()
    found = []
    for weapon in unrealsdk.find_all("WillowWeapon", exact=False):
        try:
            balance = weapon.DefinitionData.BalanceDefinition
            if weapon.Owner != controller.Pawn or balance is None:
                continue
            if balance._path_name() not in OUR_BALANCES:
                continue
        except Exception:  # noqa: BLE001 - half-destroyed actors throw on attribute access
            continue
        tail = str(weapon.Name).rsplit("_", 1)[-1]
        found.append((int(tail) if tail.isdigit() else 0, weapon))
    return sorted(found, key=lambda pair: pair[0])


def census() -> list[dict[str, Any]]:
    return [_describe(weapon) for _, weapon in _our_weapons()]


# --------------------------------------------------------------------- spawn (F26)
_SHARED_REGISTRY = "_bl2_pipeline_shared"
_restore_left = 0
_equip_due = 0.0
_equip_id: str | None = None


def _reward_backups() -> dict[str, dict[str, Any]]:
    """One reward-table registry for EVERY pipeline mod in this interpreter (F26)."""
    module = sys.modules.get(_SHARED_REGISTRY)
    if module is None:
        module = types.ModuleType(_SHARED_REGISTRY)
        module.reward_backups = {}
        sys.modules[_SHARED_REGISTRY] = module
    return module.reward_backups


def spawn(weapon_id: str, level: int | None = None, equip: bool = True) -> dict[str, Any]:
    """Hand the player one weapon of ``weapon_id``'s balance, at ``level`` (default: theirs)."""
    global _restore_left, _equip_due, _equip_id
    weapon = BY_ID.get(weapon_id)
    if weapon is None:
        return _write({"spawn": weapon_id, "error": f"unknown weapon; known: {sorted(BY_ID)}"})
    record: dict[str, Any] = {"spawn": weapon_id, "balance": weapon["balance"]}
    try:
        controller = get_pc()
        balance = unrealsdk.find_object("WeaponBalanceDefinition", weapon["balance"])
        mission = unrealsdk.find_object("MissionDefinition", SPAWN_MISSION)
        backups = _reward_backups()
        if SPAWN_MISSION not in backups:
            # the first hijack of this mission by ANY pipeline mod sees the pristine table
            backups[SPAWN_MISSION] = {
                "mission": mission,
                "game_stage": mission.GameStage,
                "reward_items": list(mission.Reward.RewardItems),
                "reward_pools": list(mission.Reward.RewardItemPools),
            }
        stage = int(level) if level else int(controller.PlayerReplicationInfo.ExpLevel)
        mission.GameStage = stage
        mission.Reward.RewardItems = [balance]
        mission.Reward.RewardItemPools = []
        before = {w._path_name() for _, w in _our_weapons()}
        controller.ServerGrantMissionRewards(mission, False)
        record["level"] = stage
        record["granted"] = [
            _describe(w) for _, w in _our_weapons() if w._path_name() not in before
        ]
        if equip:
            _equip_id, _equip_due = weapon_id, time.time() + EQUIP_DELAY
        _restore_left = RESTORE_TICKS
        restore_tick.enable()
        _hud(f"{weapon['label']} spawned at level {stage}")
    except Exception as ex:  # noqa: BLE001
        record["error"] = repr(ex)
        _log(f"spawn {weapon_id} failed: {ex!r}")
    return _write(record)


def _restore_reward() -> None:
    backup = _reward_backups().pop(SPAWN_MISSION, None)
    if backup is None:
        return  # nothing hijacked, or another pipeline mod already put the table back
    mission = backup["mission"]
    mission.GameStage = backup["game_stage"]
    mission.Reward.RewardItems = backup["reward_items"]
    mission.Reward.RewardItemPools = backup["reward_pools"]


def _equip_newest(weapon_id: str) -> str:
    controller = get_pc()
    manager = controller.GetPawnInventoryManager()
    ours = [w for _, w in _our_weapons() if _weapon_id(w.DefinitionData.BalanceDefinition._path_name()) == weapon_id]
    if not ours:
        return f"no {weapon_id} on the pawn yet"
    weapon = ours[-1]
    slot = int(weapon.QuickSelectSlot)
    if slot > 0:
        manager.EquipWeaponFromSlot(slot)
        return f"equipped slot {slot}"
    held = controller.Pawn.Weapon
    slot = int(held.QuickSelectSlot) if held is not None else 1
    manager.ReadyBackpackInventory(weapon, slot)
    manager.EquipWeaponFromSlot(slot)
    return f"readied and equipped slot {slot}"


@hook("WillowGame.WillowGameViewportClient:Tick", Type.PRE)
def restore_tick(obj: UObject, args: WrappedStruct, ret: Any, func: BoundFunction) -> None:
    """Equip the spawned weapon once it exists, and put the mission's reward table back."""
    global _restore_left, _equip_id
    if _equip_id is not None and time.time() >= _equip_due:
        weapon_id, _equip_id = _equip_id, None
        try:
            _write({"equip": weapon_id, "result": _equip_newest(weapon_id)})
        except Exception as ex:  # noqa: BLE001
            _write({"equip": weapon_id, "error": repr(ex)})
    _restore_left -= 1
    if _restore_left <= 0:
        _restore_reward()
        if _equip_id is None:
            restore_tick.disable()


# --------------------------------------------------------------------- auto sequence
#: seconds after a map load before the first auto spawn, between spawns, and before the
#: closing census (wall clock: tick counts scale with the frame rate, F25)
AUTO_DELAYS = (2.0, 2.5, 2.0)
_auto_queue: list[str] = []
_auto_deadline = 0.0
_auto_phase = ""


@hook("WillowGame.WillowPlayerController:WillowClientDisableLoadingMovie", Type.POST)
def on_map_loaded(obj: UObject, args: WrappedStruct, ret: Any, func: BoundFunction) -> None:
    """Fires once per gameplay map load (never at the title screen): census, then the
    control file's auto_spawn list, then a closing census + done."""
    global _auto_queue, _auto_deadline, _auto_phase
    try:
        _write({"census_on_load": census(), "registration": {
            k: (v.get("ok") if isinstance(v, dict) else None) for k, v in registration().items()}})
    except Exception as ex:  # noqa: BLE001
        _write({"census_on_load": None, "error": repr(ex)})
    wanted = _control().get("auto_spawn")
    if not isinstance(wanted, list) or not wanted:
        return
    _auto_queue = [str(w) for w in wanted]
    _auto_deadline = time.time() + AUTO_DELAYS[0]
    _auto_phase = "spawn"
    seq_tick.enable()
    _write({"auto_spawn": list(_auto_queue), "armed": True})


@hook("WillowGame.WillowGameViewportClient:Tick", Type.PRE)
def seq_tick(obj: UObject, args: WrappedStruct, ret: Any, func: BoundFunction) -> None:
    global _auto_queue, _auto_deadline, _auto_phase
    if not _auto_phase or time.time() < _auto_deadline:
        return
    if _auto_phase == "spawn" and _auto_queue:
        spawn(_auto_queue.pop(0))
        _auto_deadline = time.time() + AUTO_DELAYS[1]
        if not _auto_queue:
            _auto_phase = "census"
            _auto_deadline = time.time() + AUTO_DELAYS[2]
        return
    _auto_phase = ""
    seq_tick.disable()
    _write({"census": census(), "done": True})


# --------------------------------------------------------------------- console
@command("armory", description="Pipeline Armory: list, spawn or census the custom weapons")
def armory_cmd(args: Any) -> None:
    if args.action == "list":
        for weapon in WEAPONS:
            _log(f"{weapon['id']:<10} {weapon['label']:<14} {weapon['balance']}")
    elif args.action == "census":
        rows = census()
        _write({"census": rows})
        for row in rows:
            _log(json.dumps(row, default=str))
        _log(f"{len(rows)} of our weapon(s) on the pawn")
    elif args.action == "spawn":
        if not args.weapon:
            _log("usage: armory spawn <id> [--level N] [--no-equip]; ids: " + ", ".join(BY_ID))
            return
        spawn(args.weapon, args.level, not args.no_equip)


armory_cmd.add_argument("action", choices=("list", "spawn", "census"))
armory_cmd.add_argument("weapon", nargs="?", default=None, help="one of: " + ", ".join(BY_ID))
armory_cmd.add_argument("--level", type=int, default=None, help="item level (default: yours)")
armory_cmd.add_argument("--no-equip", action="store_true", help="leave it in the backpack")


# --------------------------------------------------------------------- menu + keybind
weapon_option = DropdownOption(
    "Weapon", WEAPONS[0]["label"], [w["label"] for w in WEAPONS],
    description="Which weapon 'Spawn selected' and the spawn key hand out.",
)


def _selected_id() -> str:
    return BY_LABEL.get(str(weapon_option.value), WEAPONS[0])["id"]


spawn_button = ButtonOption(
    "Spawn selected",
    description="Spawn the selected weapon at your level and equip it.",
    on_press=lambda _option: spawn(_selected_id()),
)
armory_menu = NestedOption(
    "Armory", [weapon_option, spawn_button],
    description="Spawn the pipeline weapons (also: the 'armory' console command).",
)


@keybind("$mod_name: spawn selected weapon", "$key")
def kb_spawn() -> None:
    spawn(_selected_id())


# --------------------------------------------------------------------- wiring
build_mod(
    name=MOD_NAME,
    description="$short_description",
    hooks=[restore_tick, on_map_loaded, seq_tick,
           *(h for component in COMPONENTS for h in component["hooks"])],
    keybinds=[kb_spawn],
    options=[armory_menu],
    commands=[armory_cmd],
)

# Component hooks are enabled here rather than left to the mod menu: a mod that has never
# been enabled is not auto-enabled on the launch that installs it (F8).
for _component in COMPONENTS:
    for _hook in _component["hooks"]:
        _hook.enable()
on_map_loaded.enable()
armory_cmd.enable()
_log(f"armed: {len(WEAPONS)} weapon(s) ({', '.join(BY_ID)}); registration runs at the main menu")
''')


def _weapon_rows(armory: ArmorySpec, resolved: list[ResolvedSpec]) -> str:
    rows = []
    for weapon, res in zip(armory.weapons, resolved):
        balance = res.balances[0].path
        rows.append(
            f'    {{"id": "{weapon.id}", "label": "{weapon.label}", "module": {weapon.id},\n'
            f'     "balance": "{balance}", "package": "{res.spec.package_stem}",\n'
            f'     "weapon_type": "{res.spec.weapon_type}"}},'
        )
    return "\n".join(rows)


def _weapon_summary(armory: ArmorySpec, resolved: list[ResolvedSpec]) -> str:
    lines = []
    for weapon, res in zip(armory.weapons, resolved):
        lines.append(
            f"  {weapon.id:<10} {weapon.label!r}: {res.spec.weapon_type}, package "
            f"{res.spec.package_stem}, {len(res.fragments)} fragment(s), {len(res.parts)} "
            f"part(s), balance {res.balances[0].path}"
        )
    return "\n".join(lines)


def render_armory(armory: ArmorySpec, resolved: list[ResolvedSpec], spec_name: str = "<armory>") -> str:
    """Render the Armory's ``__init__.py`` over the already-rendered component modules."""
    short = (armory.description or "Pipeline weapons in one mod, with a spawn console.")
    short = short.strip().splitlines()[0].replace('"', "'")
    if len(short) > 70:
        short = short[:67].rstrip() + "..."
    text = _ARMORY.substitute(
        mod_name=armory.name,
        count=len(armory.weapons),
        spec_name=str(spec_name).replace("\\", "/"),
        key=armory.spawn_key,
        mission=armory.spawn_mission,
        weapon_summary=_weapon_summary(armory, resolved),
        imports=", ".join(w.id for w in armory.weapons),
        version=armory.version,
        author=armory.author,
        weapons=_weapon_rows(armory, resolved),
        short_description=short,
    )
    return text if text.endswith("\n") else text + "\n"


def render_armory_pyproject(armory: ArmorySpec) -> str:
    description = (armory.description or "Pipeline weapons in one mod, with a spawn console.")
    description = description.strip().splitlines()[0].replace('"', "'")
    if len(description) > 90:
        description = description[:87].rstrip() + "..."
    author = f'\nauthors = [{{ name = "{armory.author}" }}]' if armory.author else ""
    return (
        "# Generated by bl2_partgen (armory). pyunrealsdk reads this to name the mod folder;\n"
        "# the mod itself is sdk_mods/%s/__init__.py, its weapons under weapons/.\n"
        "[project]\n"
        'name = "%s"\n'
        'version = "%s"\n'
        'description = "%s"%s\n'
        'requires-python = ">=3.11"\n'
    ) % (armory.name, armory.name, armory.version, description, author)


def render_armory_readme(
    armory: ArmorySpec, resolved: list[ResolvedSpec], spec_name: str
) -> str:
    spec_name = str(spec_name).replace("\\", "/")
    lines = [
        f"# {armory.name}",
        "",
        f"Generated by `bl2_partgen` from `{spec_name}`. Do not edit by hand: change the armory",
        "spec or a weapon's spec and re-emit (`python -m bl2_partgen <armory.json> --out <dir>`).",
        "",
        "## Install",
        "",
        "```",
        f"<game>/sdk_mods/{armory.name}/__init__.py          this mod",
        f"<game>/sdk_mods/{armory.name}/weapons/<id>.py      one component per weapon",
        f"<game>/sdk_mods/settings/{armory.name}.json        {{\"enabled\": true}}  (F8)",
    ]
    for res in resolved:
        lines.append(f"<game>/WillowGame/CookedPCConsole/{res.spec.package_stem}.upk")
        for name in res.extra_packages:
            lines.append(f"<game>/WillowGame/CookedPCConsole/{name}.upk")
    lines += [
        "```",
        "",
        "`python -m bl2_partgen <armory.json> --out <dir> --install <game dir>` does all of it.",
        "Exactly one Armory, and no separate player build of any of its weapons, may be enabled",
        "at a time: a weapon registered twice double-registers its fragments.",
        "",
        "## Spawning",
        "",
        "| how | what |",
        "|---|---|",
        "| console | `armory list`, `armory spawn <id> [--level N] [--no-equip]`, `armory census` |",
        "| menu | SDK mod menu > Armory > Weapon (dropdown), Spawn selected (button) |",
        f"| keybind | `{armory.spawn_key}` spawns the selected weapon |",
        "",
        f"A spawn borrows `{armory.spawn_mission}`'s reward table and restores it 300 ticks",
        "later through the registry every pipeline mod shares (F26).",
        "",
        "## Weapons",
        "",
        "| id | label | weapon type | package | balance |",
        "|---|---|---|---|---|",
    ]
    for weapon, res in zip(armory.weapons, resolved):
        lines.append(
            f"| `{weapon.id}` | {weapon.label} | {res.spec.weapon_type} | "
            f"`{res.spec.package_stem}` | `{res.balances[0].path}` |"
        )
    lines += [
        "",
        "## Status",
        "",
        f"* `sdk_mods/{armory.name}/status.json` - spawns, equips and censuses, appended in order",
        f"* `sdk_mods/{armory.name}/weapons/<mod name>.status.json` - each component's own "
        "registration / save round-trip records",
        "* `sdk_mods/_pipeline_saves/<package>/<save>.json` - the per-save part records (F18), "
        "shared by every build of a weapon",
        "",
    ]
    return "\n".join(lines)
